const assert = require("node:assert/strict");
const {
  RECIPIENT_SUBSCRIPTION_UNAVAILABLE,
  SENDER_SUBSCRIPTION_UNAVAILABLE,
  SEND_UNAVAILABLE,
} = require("./sendMessageGuardCodes");

assert.equal(RECIPIENT_SUBSCRIPTION_UNAVAILABLE, "RECIPIENT_SUBSCRIPTION_UNAVAILABLE");
assert.equal(SENDER_SUBSCRIPTION_UNAVAILABLE, "SENDER_SUBSCRIPTION_UNAVAILABLE");
assert.equal(SEND_UNAVAILABLE, "SEND_UNAVAILABLE");

assert.notEqual(RECIPIENT_SUBSCRIPTION_UNAVAILABLE, SENDER_SUBSCRIPTION_UNAVAILABLE);
assert.notEqual(RECIPIENT_SUBSCRIPTION_UNAVAILABLE, SEND_UNAVAILABLE);
assert.notEqual(SENDER_SUBSCRIPTION_UNAVAILABLE, SEND_UNAVAILABLE);

console.log("sendMessageGuardCodes.test.js: ok");
