const RECIPIENT_SUBSCRIPTION_UNAVAILABLE = "RECIPIENT_SUBSCRIPTION_UNAVAILABLE";
const SENDER_SUBSCRIPTION_UNAVAILABLE = "SENDER_SUBSCRIPTION_UNAVAILABLE";
const SEND_UNAVAILABLE = "SEND_UNAVAILABLE";

module.exports = {
  RECIPIENT_SUBSCRIPTION_UNAVAILABLE,
  SENDER_SUBSCRIPTION_UNAVAILABLE,
  SEND_UNAVAILABLE,
};
