const OPENAI_TRANSCRIBE_URL = "https://api.openai.com/v1/audio/transcriptions";
const OPENAI_TRANSCRIBE_MODEL = "gpt-4o-mini-transcribe";
const DEFAULT_DAILY_TRANSCRIBE_LIMIT = 120;
const MAX_AUDIO_BYTES = 2 * 1024 * 1024;
const MAX_STT_PROMPT_CHARS = 1000;
const STT_PROVIDER_OPENAI = "openai";
const STT_PROVIDER_GOOGLE = "google";
const STT_PROVIDER_GEMINI = "gemini";
const STT_PROVIDER_GROQ = "groq";
const ALLOWED_STT_PROVIDERS = new Set([
  STT_PROVIDER_OPENAI,
  STT_PROVIDER_GOOGLE,
  STT_PROVIDER_GEMINI,
  STT_PROVIDER_GROQ,
]);
const GEMINI_TRANSCRIBE_MODEL = "gemini-3.5-flash-lite";
const GROQ_TRANSCRIBE_URL =
  "https://api.groq.com/openai/v1/audio/transcriptions";
const GROQ_TRANSCRIBE_MODEL = "whisper-large-v3-turbo";
const GROQ_STT_API_TIMEOUT_MS = 25000;
const GOOGLE_STT_DEFAULT_MODEL = "chirp_3";
const GOOGLE_STT_DEFAULT_LOCATION = "us";
const GOOGLE_STT_DEFAULT_LANGUAGE = "ja-JP";
const GOOGLE_STT_API_TIMEOUT_MS = 18000;

module.exports = {
  OPENAI_TRANSCRIBE_URL,
  OPENAI_TRANSCRIBE_MODEL,
  DEFAULT_DAILY_TRANSCRIBE_LIMIT,
  MAX_AUDIO_BYTES,
  MAX_STT_PROMPT_CHARS,
  STT_PROVIDER_OPENAI,
  STT_PROVIDER_GOOGLE,
  STT_PROVIDER_GEMINI,
  STT_PROVIDER_GROQ,
  ALLOWED_STT_PROVIDERS,
  GEMINI_TRANSCRIBE_MODEL,
  GROQ_TRANSCRIBE_URL,
  GROQ_TRANSCRIBE_MODEL,
  GROQ_STT_API_TIMEOUT_MS,
  GOOGLE_STT_DEFAULT_MODEL,
  GOOGLE_STT_DEFAULT_LOCATION,
  GOOGLE_STT_DEFAULT_LANGUAGE,
  GOOGLE_STT_API_TIMEOUT_MS,
};
